import { Card, CardContent } from "@/components/ui/card";
import { TrendingUp, Users, Globe, Heart } from "lucide-react";

type Props = {};

const StatsSection = (props: Props) => {
  const stats = [
    {
      icon: <Users className="h-8 w-8 text-blue-500" />,
      value: "10K+",
      label: "Active Users",
      description: "Creators building amazing pages"
    },
    {
      icon: <Globe className="h-8 w-8 text-green-500" />,
      value: "50K+",
      label: "Pages Created",
      description: "Published and performing well"
    },
    {
      icon: <TrendingUp className="h-8 w-8 text-purple-500" />,
      value: "2M+",
      label: "Page Views",
      description: "Generated by our users"
    },
    {
      icon: <Heart className="h-8 w-8 text-pink-500" />,
      value: "99%",
      label: "Satisfaction",
      description: "Love using LinkBuilder"
    }
  ];

  return (
    <section className="py-20 px-4 md:px-10">
      <div className="text-center mb-16">
        <h2 className="text-4xl font-semibold mb-4 text-white">
          Trusted by Thousands of Creators
        </h2>
        <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
          Join a growing community of marketers, agencies, and businesses building beautiful pages
        </p>
      </div>

      <div className="grid md:grid-cols-4 gap-8 max-w-6xl mx-auto">
        {stats.map((stat, index) => (
          <Card key={index} className="bg-themeBlack border-themeGray text-center hover:border-gray-600 transition-colors">
            <CardContent className="p-8">
              <div className="flex justify-center mb-4">
                {stat.icon}
              </div>
              <div className="text-4xl font-bold text-white mb-2">
                {stat.value}
              </div>
              <div className="text-xl font-semibold text-white mb-1">
                {stat.label}
              </div>
              <div className="text-sm text-muted-foreground">
                {stat.description}
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Testimonial */}
      <div className="mt-20 max-w-4xl mx-auto">
        <Card className="bg-gradient-to-r from-purple-500/10 to-pink-500/10 border-purple-500/20">
          <CardContent className="p-8 text-center">
            <div className="text-2xl font-semibold text-white mb-4">
              "LinkBuilder transformed how we create landing pages. What used to take days now takes minutes."
            </div>
            <div className="flex items-center justify-center gap-4">
              <div className="w-12 h-12 bg-gradient-to-r from-purple-500 to-pink-500 rounded-full flex items-center justify-center text-white font-bold">
                JS
              </div>
              <div className="text-left">
                <div className="font-medium text-white">John Smith</div>
                <div className="text-sm text-muted-foreground">Marketing Director, TechCorp</div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </section>
  );
};

export default StatsSection; 